apiVersion: v1
kind: Service
metadata:
  name: geeksclub-postgres
spec:
  ports:
    - port: 5432
  selector:
    app: geeksclub-postgres-pod
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: geeksclub-postgres-deployment
spec:
  selector:
    matchLabels:
      app: geeksclub-postgres-pod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: geeksclub-postgres-pod
    spec:
      containers:
        - image: postgres
          name: postgres
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: geeksclub-postgres-secrets
                key: postgres_username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: geeksclub-postgres-secrets
                key: postgres_password
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: geeksclub-postgres-configmap
                key: postgres_database
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: geeksclub-postgres-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geeksclub-postgres-pv-claim
  labels:
    app: geeksclub-postgres-pod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi